version: '3'
services:
  db:
    image: postgres
    restart: always
    ports: 
     - "5434:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myrailsapp
    ports:
      - "3001:3001"
    depends_on:
      - db